### ISSUE TITLE
PSO +PCA model

### ISSUE THREAD

**Issue by boraster** [HandsomeHans/SVM-classification-detection#1]
Hello,

Very nice implemantation of Hog + SVM and other algorithms!!
Unfortunately, I am stuck with the 6. script where PSO and PCA algorithms because the next script where the had negative mining requires a "**svm_pso.model**" but I can only generate "svm_20pixel_pca_100.model" with the previous script (5_Test_PCA+SVM).

Can you please point out where I make mistake?

Best regards.

**Comment by HansRen1024** [comment]
@boraster 
Sorry for replying so late. Did you get clear to this issue?
See ReadMe for more suggestion.
