### ISSUE TITLE
博主，请教一个问题

### ISSUE THREAD

**Issue by a819721810** [HandsomeHans/SVM-classification-detection#2]
![image](https://user-images.githubusercontent.com/10041362/46061714-2d10cc00-c19a-11e8-88b0-fc55e3359534.png)
如果假设要在图中定位识别这种类型数据，在训练数据量少的情况下，你觉得你是用类似于你8,9,10的传统方法好，还是用Faster R-CNN/SSD之类的好，还有你这种传统的滑动窗口方法，和SIFT/SURF那种算子匹配，那种更好一点

**Comment by HansRen1024** [comment]
@a819721810 我觉得这种简单图形，用传统方法即可。滑动窗口用于寻找被试物体的位置，SIFT/SURF属于特征提取算法，不是一类概念。至于是用Hog还是SIFT/SURF，最好实测看看，我也不好说

**Comment by a819721810** [comment]
谢谢你，我试过传统方法，但是因为线的宽度或者图形大小，方向等等关系，传统方法还是不太好，所以目前想用data augmentation，再加上深度网络试试，再次谢谢你。 @HansRen1024

**Comment by HansRen1024** [comment]
@a819721810 那就试试squeezenet这种小网络，用SSD做检测。

**Comment by a819721810** [comment]
为什么要选择小网络了，不考虑Faster R-CNN什么的呢？@HansRen1024

**Comment by HansRen1024** [comment]
@a819721810 1.你只检测一类，而且目标很简单。小网络参数较少，已经可以满足你的需求，并且小网络在效率上有优势。2. Faster R-CNN这个算法很慢，训练相对也麻烦。所以推荐你使用SSD。

**Comment by a819721810** [comment]
没有，大概有40类左右，不过都是这样简单的图形构成的，这个东西像素也比较小，小的才20*20左右，所以我担心SSD检测小目标不敏感，效果不好 @HansRen1024

**Comment by HansRen1024** [comment]
@a819721810 40类问题也不大，就是像素好低啊- -。我记得Faster R-CNN最后改用了RPN，SSD就是借鉴的RPN，应该差不多吧。还是做出来看效果吧，想是想不明白的。

**Comment by a819721810** [comment]
好的，非常谢谢你
