### ISSUE TITLE
Unable to create svm_pso.model file

### ISSUE THREAD

**Issue by ashish-bhavsar-persistent** [HandsomeHans/SVM-classification-detection#3]
Hi,

When I am running 6th script, it’s not creating any svm_pso.model file and this file is required for all script(7,8,9,10). Please help me out with complete solution

**Comment by HansRen1024** [comment]
@ashish-bhavsar-persistent The 6th script is for finding best parameters, C and gamma, and not for training a model.

**Comment by ashish-bhavsar-persistent** [comment]
Ok.. Thank you for your reply, But I have one question that is how to generate svm_pso.model file?

**Comment by HansRen1024** [comment]
@ashish-bhavsar-persistent My pleasure. Please move to script 7 and go to line 97 which is for saving a trained SVM model.

**Comment by ashish-bhavsar-persistent** [comment]
on line 97 we are saving new model   **new_model_path = './models/svm_pso_hnm.model'**
And at line no 58 and 59 we require **svm_pso.model**

 58 : model_path = './models/svm_pso.model'
 59:    clf = joblib.load(model_path)

**Comment by HansRen1024** [comment]
@ashish-bhavsar-persistent After running script 6, you will get the best parameters and then run script 2 to train an origin model named "svm_pso.model" using the parameters.

**Comment by HansRen1024** [comment]
@ashish-bhavsar-persistent Please see README carefully, you could find the correct procedure in it.

**Comment by ashish-bhavsar-persistent** [comment]
@HandsomeHans Can you please do one favour for me, Please add one python file and update the code.. So it will become easy for the developers who may face this kind of issue.

**Comment by ashish-bhavsar-persistent** [comment]
@HandsomeHans  In Script 2 we are not using any better parameter and not giving path of no-pca features . So 4th Step is too confusing and unable to generate/create svm_pso.model

**Comment by HansRen1024** [comment]
@ashish-bhavsar-persistent I will update script 2 giving out a hint.

**Comment by ashish-bhavsar-persistent** [comment]
@HandsomeHans  That we be great and thank you so much :)

**Comment by HansRen1024** [comment]
@ashish-bhavsar-persistent You are welcome.

**Comment by ashish-bhavsar-persistent** [comment]
@HansRen1024 When you will update the script? Can you please do it ASAP. It will help me alot.
